// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */

/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */

// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: qLGagQ2DmgNe1FZGCaQoDb
// Component: xFvUTOZKzQi5r9
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: yXM9CiZIYNsx-O/component
import Button from "../../Button"; // plasmic-import: ibhXG1eT3AC1_w/component
import Price from "../../Price"; // plasmic-import: 0SV_oavTjieGna/component
import Separator from "../../Separator"; // plasmic-import: VjAhTiuoEtasmb/component
import ProductCard from "../../ProductCard"; // plasmic-import: 1HK41xgc8bfpgp/component
import Footer from "../../Footer"; // plasmic-import: NmbnAqSDZSY-2F/component

import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: XGY7GHA_yxuwnI/globalVariant

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: qLGagQ2DmgNe1FZGCaQoDb/projectcss
import * as sty from "./PlasmicItem.module.css"; // plasmic-import: xFvUTOZKzQi5r9/css

import Icon24Icon from "./icons/PlasmicIcon__Icon24"; // plasmic-import: IfrVYWixZqHYop/icon
import IconIcon from "./icons/PlasmicIcon__Icon"; // plasmic-import: OCsEn4tAW1V0oo/icon
import Icon25Icon from "./icons/PlasmicIcon__Icon25"; // plasmic-import: lG_1oHU7hGJcq-/icon
import Icon26Icon from "./icons/PlasmicIcon__Icon26"; // plasmic-import: IU_hfD5G0jvbCc/icon
import Icon5Icon from "./icons/PlasmicIcon__Icon5"; // plasmic-import: Q9jbpX4a56-1Zy/icon
import Icon22Icon from "./icons/PlasmicIcon__Icon22"; // plasmic-import: vyJDz4S_jOJLG7/icon
import Icon21Icon from "./icons/PlasmicIcon__Icon21"; // plasmic-import: mxjvaOqQSldmVn/icon
import Icon20Icon from "./icons/PlasmicIcon__Icon20"; // plasmic-import: CmtivnEQ5n--QT/icon

export type PlasmicItem__VariantMembers = {};

export type PlasmicItem__VariantsArgs = {};
type VariantPropType = keyof PlasmicItem__VariantsArgs;
export const PlasmicItem__VariantProps = new Array<VariantPropType>();

export type PlasmicItem__ArgsType = {
  container42?: React.ReactNode;
  children4?: React.ReactNode;
  children24?: React.ReactNode;
  children224?: React.ReactNode;
  children2224?: React.ReactNode;
  children22224?: React.ReactNode;
  children222223?: React.ReactNode;
};

type ArgPropType = keyof PlasmicItem__ArgsType;
export const PlasmicItem__ArgProps = new Array<ArgPropType>(
  "container42",
  "children4",
  "children24",
  "children224",
  "children2224",
  "children22224",
  "children222223"
);

export type PlasmicItem__OverridesType = {
  root?: p.Flex<"div">;
  navBar?: p.Flex<typeof NavBar>;
  container432?: p.Flex<"div">;
  container4322?: p.Flex<"div">;
  price?: p.Flex<typeof Price>;
  container42?: p.Flex<"div">;
  container5?: p.Flex<"div">;
  footer?: p.Flex<typeof Footer>;
  textbox?: p.Flex<"input">;
};

export interface DefaultItemProps {
  dataFetches: PlasmicItem__Fetches;
}

function PlasmicItem__RenderFunc(props: {
  variants: PlasmicItem__VariantsArgs;
  args: PlasmicItem__ArgsType;
  overrides: PlasmicItem__OverridesType;
  dataFetches?: PlasmicItem__Fetches;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode, dataFetches } = props;

  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <Head>
        <title key="title">{"Item"}</title>
        <meta key="og:title" property="og:title" content={"Item"} />
        <meta
          key="description"
          name="description"
          property="og:description"
          content={
            "Nunc parturient ultricies condimentum parturient sagittis urna mus conubia himenaeos fermentum leo mus dignissim pulvinar blandit porta eget ad."
          }
        />
      </Head>

      <style>{`
        body {
          margin: 0;
        }
      `}</style>

      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
          />

          <section className={classNames(defaultcss.all, sty.section___7ZmkR)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container432"}
              data-plasmic-override={overrides.container432}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container432)}
            >
              <Button icons={"none" as const} slot={"Mens"}>
                <Icon24Icon
                  className={classNames(defaultcss.all, sty.svg__lZFX)}
                  role={"img"}
                />
              </Button>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__j4FmW
                )}
              >
                {"/"}
              </div>

              <Button icons={"none" as const} slot={"Shoes"}>
                <Icon24Icon
                  className={classNames(defaultcss.all, sty.svg__k8VG4)}
                  role={"img"}
                />
              </Button>

              <div
                className={classNames(
                  defaultcss.all,
                  defaultcss.__wab_text,
                  sty.box__xlY4W
                )}
              >
                {"/"}
              </div>

              <Button icons={"none" as const} slot={"Running"}>
                <Icon24Icon
                  className={classNames(defaultcss.all, sty.svg__idkTx)}
                  role={"img"}
                />
              </Button>
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__gUm4E)}>
            <p.Stack
              as={"div"}
              data-plasmic-name={"container4322"}
              data-plasmic-override={overrides.container4322}
              hasGap={true}
              className={classNames(defaultcss.all, sty.container4322)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__muvmW)}
              >
                <img
                  alt={""}
                  className={classNames(defaultcss.img, sty.img__m0Mdi)}
                  role={"img"}
                  src={
                    "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/194681/02/sv01/fnd/PNA/fmt/png/Eternity-NITRO-Men's-Running-Shoes" as const
                  }
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__fQLqE)}
                >
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__fopb)}
                    role={"img"}
                    src={
                      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/194681/02/mod03/fnd/PNA/fmt/png/Eternity-NITRO-Men's-Running-Shoes" as const
                    }
                  />

                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__buyJ4)}
                    role={"img"}
                    src={
                      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/194681/02/sv01/fnd/PNA/fmt/png/Eternity-NITRO-Men's-Running-Shoes" as const
                    }
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__xGpb)}
                >
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__h5V2Z)}
                    role={"img"}
                    src={
                      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/194681/02/bv/fnd/PNA/fmt/png/Eternity-NITRO-Men's-Running-Shoes" as const
                    }
                  />

                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__zhEaG)}
                    role={"img"}
                    src={
                      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/194681/02/sv02/fnd/PNA/fmt/png/Eternity-NITRO-Men's-Running-Shoes" as const
                    }
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__yd5Zn)}
                >
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__aXc20)}
                    role={"img"}
                    src={
                      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/194681/02/sv03/fnd/PNA/fmt/png/Eternity-NITRO-Men's-Running-Shoes" as const
                    }
                  />

                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__zrcpb)}
                    role={"img"}
                    src={
                      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/194681/02/sv04/fnd/PNA/fmt/png/Eternity-NITRO-Men's-Running-Shoes" as const
                    }
                  />
                </p.Stack>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__hXgMl)}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    defaultcss.__wab_text,
                    sty.box__mU76
                  )}
                >
                  {"Eternity NITRO Men's Running Shoes"}
                </div>

                <Price
                  data-plasmic-name={"price"}
                  data-plasmic-override={overrides.price}
                  className={classNames("__wab_instance", sty.price)}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__fqo3R)}
                >
                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img___3G7GW)}
                    role={"img"}
                    src={
                      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_450,h_450/global/194681/03/sv01/fnd/PNA/fmt/png" as const
                    }
                  />

                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__a5Npn)}
                    role={"img"}
                    src={
                      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_450,h_450/global/194681/01/sv01/fnd/PNA/fmt/png" as const
                    }
                  />

                  <img
                    alt={""}
                    className={classNames(defaultcss.img, sty.img__lb5Ji)}
                    role={"img"}
                    src={
                      "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_450,h_450/global/194681/02/sv01/fnd/PNA/fmt/png" as const
                    }
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__rk8A)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box___2JHcO
                    )}
                  >
                    {"Size"}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__tGVU)}
                  >
                    <Button
                      colors={"lightGrayOutline" as const}
                      icons={"none" as const}
                      slot={"7"}
                    />

                    <Button
                      colors={"lightGrayOutline" as const}
                      icons={"none" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__xu5EG
                          )}
                        >
                          {"7.5"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline" as const}
                      icons={"none" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__qpQ5Z
                          )}
                        >
                          {"8"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline" as const}
                      icons={"none" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__dgSbz
                          )}
                        >
                          {"8.5"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline" as const}
                      icons={"none" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__sYu6
                          )}
                        >
                          {"9"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline" as const}
                      icons={"none" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__cqAmx
                          )}
                        >
                          {"9.5"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline" as const}
                      icons={"none" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__zl9F4
                          )}
                        >
                          {"10"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline" as const}
                      icons={"none" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__kxBPq
                          )}
                        >
                          {"10.5"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline" as const}
                      icons={"none" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__m5Wzg
                          )}
                        >
                          {"11"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline" as const}
                      icons={"none" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__kDdoj
                          )}
                        >
                          {"11.5"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline" as const}
                      icons={"none" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__dVvG6
                          )}
                        >
                          {"12"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline" as const}
                      icons={"none" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__rmwpJ
                          )}
                        >
                          {"13"}
                        </div>
                      }
                    />

                    <Button
                      colors={"lightGrayOutline" as const}
                      icons={"none" as const}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__dQmR
                          )}
                        >
                          {"14"}
                        </div>
                      }
                    />
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__d169)}
                >
                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__ea3A8)}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__nt0Ki
                      )}
                    >
                      {"Quantity"}
                    </div>

                    <Button
                      children2={
                        <Icon25Icon
                          className={classNames(defaultcss.all, sty.svg__kfsNc)}
                          role={"img"}
                        />
                      }
                      className={classNames(
                        "__wab_instance",
                        sty.button__pt0SY
                      )}
                      colors={"lightGrayOutline" as const}
                      icons={"end" as const}
                      slot={"1"}
                    />
                  </p.Stack>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__gXci)}
                  >
                    <Button
                      colors={"lightGrayOutline" as const}
                      icons={"only" as const}
                      size={"large" as const}
                      slot={"Add to cart"}
                    >
                      <Icon26Icon
                        className={classNames(defaultcss.all, sty.svg__nhJQ)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      colors={"black" as const}
                      icons={"none" as const}
                      link2={"/cart" as const}
                      rounded={"rounded" as const}
                      size={"large" as const}
                      slot={"Add to cart"}
                    />
                  </p.Stack>
                </p.Stack>

                <Separator
                  className={classNames("__wab_instance", sty.separator__psPtG)}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__gskuA)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__nLdbN
                    )}
                  >
                    {"Description"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__onAh4
                    )}
                  >
                    {
                      "Let Eternity NITRO be your guide. The engineered mesh upper integrates the runGUIDE tech, designed to hug your midfoot for an effortless ride. For the midsole, NITRO foam provides superior cushioning, combining with other tech elements to give you support: a TPU heel piece for proprioception, reflectivity, and a durable rubber PUMAGRIP for all-surface traction. You lead the way, Eternity NITRO will keep you in line."
                    }
                  </div>
                </p.Stack>

                <Separator
                  className={classNames("__wab_instance", sty.separator__wnWIo)}
                />

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__tDFvA)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__m18Hx
                    )}
                  >
                    {"Details"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__ypzUp
                    )}
                  >
                    {"Adaptive fit with midfoot wrap for secure lockdown"}
                  </div>

                  <Separator
                    className={classNames(
                      "__wab_instance",
                      sty.separator__iZfS
                    )}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__mgdjl
                    )}
                  >
                    {"Engineered mesh upper for support"}
                  </div>

                  <Separator
                    className={classNames(
                      "__wab_instance",
                      sty.separator__lwpV
                    )}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__k5H4P
                    )}
                  >
                    {"Full lace closure for snug fit"}
                  </div>

                  <Separator
                    className={classNames(
                      "__wab_instance",
                      sty.separator__ffSg
                    )}
                  />

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__uU9JK
                    )}
                  >
                    {
                      "NITRO FOAM midsole for lightweight, responsive cushioning"
                    }
                  </div>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </section>

          <section className={classNames(defaultcss.all, sty.section__yymCo)}>
            <div
              data-plasmic-name={"container42"}
              data-plasmic-override={overrides.container42}
              className={classNames(defaultcss.all, sty.container42)}
            >
              {p.renderPlasmicSlot({
                defaultContents: (
                  <div className={classNames(defaultcss.all, sty.box__f72Ta)}>
                    <div
                      className={classNames(
                        defaultcss.all,
                        defaultcss.__wab_text,
                        sty.box__hO8XN
                      )}
                    >
                      {"You may also like"}
                    </div>

                    <Button
                      children2={
                        <Icon5Icon
                          className={classNames(defaultcss.all, sty.svg__vusnZ)}
                          role={"img"}
                        />
                      }
                      className={classNames(
                        "__wab_instance",
                        sty.button___73Iq7
                      )}
                      icons={"end" as const}
                      link={"link" as const}
                      slot={"See more"}
                    />
                  </div>
                ),

                value: args.container42
              })}
            </div>

            <div
              data-plasmic-name={"container5"}
              data-plasmic-override={overrides.container5}
              className={classNames(defaultcss.all, sty.container5)}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(defaultcss.all, sty.box__uZvA)}
              >
                <ProductCard
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__rzgGe)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/1070aebbb55841e1aae5ac9f00b39879_9366/adidas_Ultraboost_DNA_x_LEGO(r)_Plates_Shoes_White_FY7690_01_standard.jpg" as const
                        }
                      />
                    ),

                    value: args.children4
                  })}
                  link={"http://google.com" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__r2ENp
                    )}
                  >
                    {"ADIDAS ULTRABOOST DNA X LEGO® PLATES SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__vmfwh
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__auwlw
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__knfCp)}
                        role={"img"}
                        src={
                          "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/79d40e0b-da9d-4049-a4be-6a8fe7d9489e/air-zoom-pegasus-38-womens-running-shoe-2bvJvW.png" as const
                        }
                      />
                    ),

                    value: args.children24
                  })}
                  link={"/item" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__l9Bat
                    )}
                  >
                    {"Nike Air Zoom Pegasus 38"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__l47Aj
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__nf6Rv
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__w6O1S)}
                        role={"img"}
                        src={
                          "https://assets.reebok.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/3108369a42714ba6a9c2aa99017b457a_9366/Club_C_85_Vintage_Men's_Shoes_White_V67899_01_standard.jpg" as const
                        }
                      />
                    ),

                    value: args.children224
                  })}
                  link={"/item" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__u2Skw
                    )}
                  >
                    {"Club C 85 Vintage Men's Shoes"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__lQaR0
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__as2A1
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img___6GhgM)}
                        role={"img"}
                        src={
                          "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/b13d4f77-9404-492f-b2c8-5f06419f2cb6/air-max-genome-mens-shoe-hgsQFb.png" as const
                        }
                      />
                    ),

                    value: args.children2224
                  })}
                  link={"/item" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__qbp7A
                    )}
                  >
                    {"Nike Air Max Genome"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__lr7K
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__j2PIk
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img___0QiR)}
                        role={"img"}
                        src={
                          "https://assets.adidas.com/images/h_840,f_auto,q_auto:sensitive,fl_lossy/cdfdf1409e054322b9e0ac6d011da5e2_9366/Ultraboost_DNA_1.0_Shoes_Green_H05264_01_standard.jpg" as const
                        }
                      />
                    ),

                    value: args.children22224
                  })}
                  link={"/item" as const}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__oiqp8
                    )}
                  >
                    {"ULTRABOOST DNA 1.0 SHOES"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__wO4So
                    )}
                  >
                    {"If you can dream it, you can build it."}
                  </div>
                </ProductCard>

                <ProductCard
                  className={classNames(
                    "__wab_instance",
                    sty.productCard__y75M2
                  )}
                  image={p.renderPlasmicSlot({
                    defaultContents: (
                      <img
                        alt={""}
                        className={classNames(defaultcss.img, sty.img__s99Vb)}
                        role={"img"}
                        src={
                          "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5,q_80/f6cbde42-eed6-42bd-b5d9-1b5bef129618/zion-1-big-kids-shoe-BsvRq7.png" as const
                        }
                      />
                    ),

                    value: args.children222223
                  })}
                  link={"/item" as const}
                />
              </p.Stack>
            </div>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
            container432={
              <React.Fragment>
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__itW4W)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__y9Enz
                    )}
                  >
                    {"Subscribe"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__chMmh
                    )}
                  >
                    {
                      "Sign up for exclusive offers, original stories, activism, events and more."
                    }
                  </div>

                  <input
                    data-plasmic-name={"textbox"}
                    data-plasmic-override={overrides.textbox}
                    className={classNames(defaultcss.input, sty.textbox)}
                    placeholder={"Email address…" as const}
                    size={1 as const}
                    type={"text" as const}
                    value={"" as const}
                  />

                  <Button
                    className={classNames("__wab_instance", sty.button__cuqZa)}
                    colors={"black" as const}
                    icons={"none" as const}
                    slot={"Sign me up"}
                  />
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__spwl6)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__yiNEx
                    )}
                  >
                    {"Help"}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(defaultcss.all, sty.box__qy9Ws)}
                  >
                    <Button slot={"Order status"}>
                      <Icon22Icon
                        className={classNames(defaultcss.all, sty.svg___5Pf5B)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__kEpBx
                      )}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box___4UHrx
                          )}
                        >
                          {"Returns and exchanges"}
                        </div>
                      }
                    >
                      <Icon21Icon
                        className={classNames(defaultcss.all, sty.svg__edtVw)}
                        role={"img"}
                      />
                    </Button>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__yKoSi
                      )}
                      slot={
                        <div
                          className={classNames(
                            defaultcss.all,
                            defaultcss.__wab_text,
                            sty.box__wbby1
                          )}
                        >
                          {"Help center"}
                        </div>
                      }
                    >
                      <Icon20Icon
                        className={classNames(defaultcss.all, sty.svg__xOvEc)}
                        role={"img"}
                      />
                    </Button>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(defaultcss.all, sty.box__aeRe)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      defaultcss.__wab_text,
                      sty.box__kr1W4
                    )}
                  >
                    {"More info"}
                  </div>

                  <div className={classNames(defaultcss.all, sty.box__vHwE2)}>
                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__mVbLo)}
                    >
                      <Button icons={"none" as const} slot={"Gift cards"} />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__lkcOd
                        )}
                        icons={"none" as const}
                        slot={"Find a store"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__dnfOz
                        )}
                        icons={"none" as const}
                        slot={"Careers"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__dynKr
                        )}
                        icons={"none" as const}
                        slot={"Sitemap"}
                      />
                    </p.Stack>

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(defaultcss.all, sty.box__qWoam)}
                    >
                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__mMv4H
                        )}
                        icons={"none" as const}
                        slot={"Group sales"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__qoRj1
                        )}
                        icons={"none" as const}
                        slot={"Privacy policy"}
                      />

                      <Button
                        className={classNames(
                          "__wab_instance",
                          sty.button__ixpv5
                        )}
                        icons={"none" as const}
                        slot={"Contact us"}
                      />
                    </p.Stack>
                  </div>
                </p.Stack>
              </React.Fragment>
            }
          />
        </div>
      </div>
    </React.Fragment>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "container432",
    "container4322",
    "price",
    "container42",
    "container5",
    "footer",
    "textbox"
  ],
  navBar: ["navBar"],
  container432: ["container432"],
  container4322: ["container4322", "price"],
  price: ["price"],
  container42: ["container42"],
  container5: ["container5"],
  footer: ["footer", "textbox"],
  textbox: ["textbox"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<T extends NodeNameType> =
  typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  navBar: typeof NavBar;
  container432: "div";
  container4322: "div";
  price: typeof Price;
  container42: "div";
  container5: "div";
  footer: typeof Footer;
  textbox: "input";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicItem__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> =
  // Explicitly specify variants, args, and overrides as objects
  {
    variants?: PlasmicItem__VariantsArgs;
    args?: PlasmicItem__ArgsType;
    overrides?: NodeOverridesType<T>;
    dataFetches?: PlasmicItem__Fetches;
  } & Omit<PlasmicItem__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
    // Specify args directly as props
    Omit<PlasmicItem__ArgsType, ReservedPropsType> &
    // Specify overrides for each element directly as props
    Omit<
      NodeOverridesType<T>,
      ReservedPropsType | VariantPropType | ArgPropType
    > &
    // Specify props for the root element
    Omit<
      Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
      ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
    >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicItem__ArgProps,
      internalVariantPropNames: PlasmicItem__VariantProps
    });

    const { dataFetches } = props;

    return PlasmicItem__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicItem";
  } else {
    func.displayName = `PlasmicItem.${nodeName}`;
  }
  return func;
}

export const PlasmicItem = Object.assign(
  // Top-level PlasmicItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    container432: makeNodeComponent("container432"),
    container4322: makeNodeComponent("container4322"),
    price: makeNodeComponent("price"),
    container42: makeNodeComponent("container42"),
    container5: makeNodeComponent("container5"),
    footer: makeNodeComponent("footer"),
    textbox: makeNodeComponent("textbox"),

    // Metadata about props expected for PlasmicItem
    internalVariantProps: PlasmicItem__VariantProps,
    internalArgProps: PlasmicItem__ArgProps
  }
);

export default PlasmicItem;
/* prettier-ignore-end */
